---
- name: 'variables - ensure validated'
  assert:
    that:
      - "lookup('vars', item.a, defaults='NOT DEFINED') {{ item.b }}"
    fail_msg: "{{ item.a }}
      == '{{ lookup('vars', item.a, defaults='NOT DEFINED') }}'"
    quiet: true
  loop_control:
    label: '{{ item.a }}'
  loop:
    - a: 'podman__repositories_manage'
      b: 'is boolean'
    - a: 'podman__repositories_state'
      b: "in ['present', 'absent']"
    - a: 'podman__repositories_enabled'
      b: 'is boolean'
    - a: 'podman__packages_manage'
      b: 'is boolean'
    - a: 'podman__packages_state'
      b: "in ['present', 'absent']"
    - a: 'podman__packages'
      b: 'is sequence'
