---
- name: "install variables - ensure validated"
  assert:
    that:
      - "{{ item.test }}"
    quiet: True
  loop:
    - test: "{{ podman__packages_state in ['present', 'absent'] }}"
      msg: "podman__packages_state in ['present', 'absent'] ->
        '{{ podman__packages_state }}'"
    - test: "{{ podman__packages | type_debug == 'list' }}"
      msg: "podman__packages is list -> '{{ podman__packages }}'"
  loop_control:
    label: "{{ item.msg }}"

- name: "packages - ensure state"
  package:
    name: "{{ podman__packages }}"
    state: "{{ podman__packages_state }}"
