---
- name: "install variables - ensure validated"
  assert:
    that:
      - "{{ item.result }}"
    quiet: "{{ podman__quiet }}"
  loop:
    - result: "{{ podman__packages_state in ['present', 'absent'] }}"
      description: "podman__packages_state in ['present', 'absent']"
      value: "{{ podman__packages_state }}"
    - result: "{{ podman__packages | type_debug == 'list' }}"
      description: "podman__packages is list"
      value: "{{ podman__packages | type_debug }}"
  loop_control:
    label: "{{ item.description }}"

- name: "packages - ensure state"
  package:
    name: "{{ podman__packages }}"
    state: "{{ podman__packages_state }}"
