---
- name: 'OS family specific variables - ensure included'
  include_vars: '{{ ansible_os_family }}.yml'
  tags: 'podman'

- import_tasks: 'validate.yml'
  tags: 'podman'

- import_tasks: 'repositories.yml'
  tags: ['podman', 'online']
  when: podman__repositories_manage

- import_tasks: 'packages.yml'
  tags: ['podman', 'online']
  when: podman__packages_manage
