---
- name: "main variables - ensure validated"
  assert:
    that:
      - "{{ item.result }}"
    quiet: "{{ podman__quiet }}"
  loop:
    - result: "{{ podman__repository_manage is boolean }}"
      description: "podman__repository_manage is boolean"
      value: "{{ podman__repository_manage }}"
    - result: "{{ podman__packages_manage is boolean }}"
      description: "podman__packages_manage is boolean"
      value: "{{ podman__packages_manage }}"
  loop_control:
    label: "{{ item.description }}"
  tags: podman

- name: "OS family specific variables - ensure included"
  include_vars: "{{ ansible_os_family }}.yml"
  tags: podman

- import_tasks: repository.yml
  when: podman__repository_manage|bool
  tags: podman, online

- import_tasks: install.yml
  when: podman__packages_manage|bool
  tags: podman, online
