---
- name: "repository variables - ensure validated"
  assert:
    that:
      - "{{ item.test }}"
    quiet: True
  loop:
    - test: "{{ podman__repository_state in ['present', 'absent'] }}"
      msg: "podman__repository_state in ['present', 'absent'] ->
        '{{ podman__repository_state }}'"
    - test: "{{ podman__repository_enabled is boolean }}"
      msg: "podman__repository_enabled is boolean ->
        '{{ podman__repository_enabled }}'"
  loop_control:
    label: "{{ item.msg }}"

- name: "distribution specific repository file - ensure included"
  include_tasks: "repository_{{ ansible_distribution
    | replace(' ', '-') | lower }}.yml"
