---
- name: "repository variables - ensure validated"
  assert:
    that:
      - "{{ item.result }}"
    quiet: "{{ podman__quiet }}"
  loop:
    - result: "{{ podman__repository_state in ['present', 'absent'] }}"
      msg: "podman__repository_state in ['present', 'absent']"
      value: "{{ podman__repository_state }}"
    - result: "{{ podman__repository_enabled is boolean }}"
      msg: "podman__repository_enabled is boolean"
      value: "{{ podman__repository_enabled }}"
  loop_control:
    label: "{{ item.msg }}"

- name: "distribution specific repository file - ensure included"
  include_tasks: "repository_{{ ansible_distribution
    | replace(' ', '-') | lower }}.yml"
