---
- name: 'debian version - ensure checked'
  assert:
    that:
      - "lookup('vars', item.a, defaults='NOT DEFINED') {{ item.b }}"
    fail_msg: "{{ item .a }}
      == '{{ lookup('vars', item.a, defaults='NOT DEFINED') }}'"
    quiet: True
  loop_control:
    label: '{{ item.a }}'
  loop:
    - a: 'ansible_distribution_version'
      b: "in ['10', 'testing']"

# To prevent following error for apt_key:
#   Failed to find required executable gpg in paths:
#   /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
- name: 'gpg - ensure installed'
  package:
    name: 'gpg'
    state: 'present'

- name: 'apt_key - ensure configured'
  apt_key:
    id: '2472D6D0D2F66AF87ABA8DA34D64390375060AA4'
    url: "https://download.opensuse.org/repositories/devel:/kubic:/\
      libcontainers:/stable/Debian_{{ ansible_distribution_version
      | capitalize }}/Release.key"
    state: '{{ podman__repositories_state }}'

- name: 'apt_repository - ensure configured'
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/\
      libcontainers:/stable/Debian_{{ ansible_distribution_version
      | capitalize }}/ /"
    state: '{{ podman__repositories_state }}'
