---
- block:
    - name: 'debian version - ensure checked'
      assert:
        that:
          - "ansible_distribution_version in ['10', 'testing']"
        quiet: true
  rescue:
    - name: 'debian version value - ensure output'
      debug:
        msg: "{{ lookup('vars', item) }}"
      loop:
        - 'ansible_distribution_version'
    - name: 'debian version unsupported -> fail'
      fail:
        msg: 'check last 2 tasks'

# To prevent following error for apt_key:
#   Failed to find required executable gpg in paths:
#   /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
- name: 'gpg - ensure installed'
  package:
    name: 'gpg'
    state: 'present'

- name: 'apt_key - ensure configured'
  apt_key:
    id: '2472D6D0D2F66AF87ABA8DA34D64390375060AA4'
    url: "https://download.opensuse.org/repositories/devel:/kubic:/\
      libcontainers:/stable/Debian_{{ ansible_distribution_version
      | capitalize }}/Release.key"
    state: '{{ podman__repositories_state }}'

- name: 'apt_repository - ensure configured'
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/\
      libcontainers:/stable/Debian_{{ ansible_distribution_version
      | capitalize }}/ /"
    state: '{{ podman__repositories_state }}'
