---
- name: "debian version - ensure checked"
  assert:
    that:
      - "{{ item.result }}"
    quiet: "{{ podman__quiet }}"
  loop:
    - result: "{{ ansible_distribution_version in ['10', 'testing'] }}"
      description: "ansible_distribution_version in ['10', 'testing']"
      value: "{{ ansible_distribution_version }}"
  loop_control:
    label: "{{ item.description }}"

- name: "apt_repository - ensure configured"
  apt_repository:
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/\
      libcontainers:/stable/Debian_{{ ansible_distribution_version
      | capitalize }}/ /"
    state: "{{ podman__repository_state }}"
    update_cache: False

# To prevent following error for apt_key:
#   Failed to find required executable gpg in paths:
#   /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
- name: "gpg - ensure installed"
  package:
    state: present
    name: gpg

- name: "apt_key - ensure configured"
  apt_key:
    id: "2472D6D0D2F66AF87ABA8DA34D64390375060AA4"
    url: "https://download.opensuse.org/repositories/devel:/kubic:/\
      libcontainers:/stable/Debian_{{ ansible_distribution_version
      | capitalize }}/Release.key"
    state: "{{ podman__repository_state }}"

- name: "apt cache - ensure updated"
  apt:
    update_cache: True
