---
dependency:
  name: 'galaxy'
  options:
    role-file: 'requirements.yml'
driver:
  name: 'vagrant'
  provider:
    name: 'libvirt'
lint: 'pre-commit run -a'
platforms:
  # https://app.vagrantup.com/boxes/search
  - name: '${USER}-podman-leap-15.2'
    box: 'opensuse/Leap-15.2.x86_64'
    box_version: '15.2.31.186'
  - name: '${USER}-podman-bullseye'
    box: 'debian/testing64'
    box_version: '20200607.1'
scenario:
  destroy_sequence:
    - 'cleanup'
    - 'destroy'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: '/usr/bin/python3'
      stdout_callback: 'yaml'
      callback_whitelist: 'profile_tasks,timer'
verifier:
  name: 'ansible'
