---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  # https://app.vagrantup.com/boxes/search
  - name: ansible-role-podman-leap-15.2
    box: opensuse/Leap-15.2.x86_64
    box_version: 15.2.31.186
  - name: ansible-role-podman-debian-10
    box: debian/buster64
    box_version: 10.4.0
  - name: ansible-role-podman-debian-11
    box: debian/testing64
    box_version: 20200607.1
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: /usr/bin/python3
      stdout_callback: yaml
verifier:
  name: ansible
